### ISSUE TITLE
Replace useless notifications view and hide count

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-twitter#103]
I don't know about yours, but my Notifications view looks like this:

![](https://user-images.githubusercontent.com/1402241/39350494-8a597004-4a28-11e8-9329-185d980ffb47.jpg)

Do you see anything that I should be notified about? I don't. It's become a duplicate Newsfeed.

Today I had "7 notifications" and none of them actually mentioned me or was in any way related to me.

How about redirecting "Notifications" to "[Mentions](https://twitter.com/mentions)" (which is the old notifications minus "Person liked/retweeted/followed you") and dropping the useless notifications count from the tab.

**Comment by sindresorhus** [comment]
I like the idea, but I think it's going to be quite controversial. Let's hear what the other maintainers think. // @filipekiss @jorgegonzalez

**Comment by filipekiss** [comment]
I don't mind the redirect to the "Mentions" tab, but dropping the notifications count from the tab might be a problem, because I don't think there's a way to alert the user when he was mentioned and we could impact people in a negative way ("I missed a mention because I don't have the notifications indicator anymore").

Maybe we can do the redirect and add an opt-out if the user doesn't want to hide the notification count?

**Comment by filipekiss** [comment]
Exactly my point. I often peek at the tweet tab only to check if there's messages or notifications, otherwise I won't bother. I've tweaked my settings to show me only notifications I'm interested about, so things like "Recent Tweets from John Doe" don't even appear.

**Comment by fregante** [comment]
Alternatively, it could target and hide the useless events directly:

```js
for (const button of document.querySelectorAll('.ActivityItem-dismissOption')) {
	button.click()
	button.closest('.stream-item').remove()
}
```

**Comment by fregante** [comment]
I'm not seeing this anymore
