### ISSUE TITLE
Feature Request | Discussion —  Automatic Twitter Threads

### ISSUE THREAD

**Issue by gdad-s-river** [sindresorhus/refined-twitter#120]
Right now, making a twitter thread is cumbersome in that, a Twitter use has to tweet, then go to that tweet then keep replying to previous tweets in order to form a twitter thread.

What if we could — 

1. Give extension options for a user to include their twitter app credentials, namely `consumer_key`, `consumer_secret`, `access_token`, `access_token_secret`

2. Give them the ability to write the whole message beyond 280 characters in one go in the tweet box.

3. Handle that big message by breaking it into chunks and use [twitter api](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update.html) to create a twitter thread out of those message chunks, using `in_reply_to_status_id` option.

Seeking opinions.

**Comment by filipekiss** [comment]
Twitter already has a native threading feature: Type the first tweet and, instead of publishing it, click the **`+`** button:

![image](https://user-images.githubusercontent.com/48519/41287952-e4e43610-6e1a-11e8-9d13-b5e5d5819802.png)

A modal window opens that allows you to keep adding to the thread before posting it:

![image](https://user-images.githubusercontent.com/48519/41287963-f4023df4-6e1a-11e8-9942-ad1cb365e958.png)

There's no need to add this to the extension.

**Comment by gdad-s-river** [comment]
O crap! :D how did I not know that 🙈
