### ISSUE TITLE
Remove tweets containing embedded tweets from muted/blocked people, or otherwise unavailable

### ISSUE THREAD

**Issue by hmemcpy** [sindresorhus/refined-twitter#122]
Sometimes, I see quoted tweets on my timeline that contain unavailable tweets, e.g.
![image](https://user-images.githubusercontent.com/601206/41528369-93e591be-72f2-11e8-8267-1c52dba16c0c.png)

After a short glance, it happens that the tweet is from a person I have blocked/muted.

I would like those tweets, quoting muted/blocked/deleted tweets (which appear as "unavailable" to be removed from the timeline.

Would this be a feature PR you'd accept?

**Comment by filipekiss** [comment]
I'm not sure about this. Sometimes, I do get some "unavailable" tweets but it's not from people I've blocked/muted (or have blocked me) but it's from an account that is new or has no verified e-mail and twitter doesn't consider it "worth", or even accounts that have the flag as "I post sensitive media" and those tweets are not automatically embedded, but I'd still like to see those. If there's a way to tell them apart, great, but If not I'd be against that because it would make users miss some tweets that they may be interested in.

**Comment by jorgegonzalez** [comment]
Yeah I think removing these would make a lot of things very confusing.
