### ISSUE TITLE
Remove "In case you missed ..." notifications?

### ISSUE THREAD

**Issue by jaddison** [sindresorhus/refined-twitter#149]
I don't think this option exists yet?

![screen shot 2018-10-11 at 1 00 46 pm](https://user-images.githubusercontent.com/101148/46830517-b35e0e00-cd55-11e8-9fc3-9cfa65d346e8.png)

Related to #103

**Comment by sindresorhus** [comment]
Good idea. PR welcome.

**Comment by thedeany** [comment]
@sindresorhus, should this new option be only for the "In case you missed..." notifications? I ask because there is a `.with-contextTweet` class on the following types of notifications in addition to "In case you missed..." notifications.

- [name] liked a...
- [name] Retweeted...
- Recent Tweet from [name]
- [name] Tweeted after a while

If these are going to be added as one option, I could use the `.with-contextTweet` class to target them. Otherwise, I'll target only the notifications with "In case you missed..." in them.

**Comment by sindresorhus** [comment]
> should this new option be only for the "In case you missed..." notifications?

Yes, the feature should be focused.

**Comment by jaddison** [comment]
Although I could see an option for each of the following you mentioned being well received by users:

>[name] liked a...
>[name] Retweeted...
>Recent Tweet from [name]
>[name] Tweeted after a while

**Comment by sindresorhus** [comment]
Yes, but should be individual options. I think we have at least some of those implemented already.

**Comment by thedeany** [comment]
If I add each of those as an option (if they're not already implemented), should they be separate PRs?

**Comment by thedeany** [comment]
I made a PR for this specific feature. Let me know if the others should be separate PRs as well and I can take a look at them!

**Comment by sindresorhus** [comment]
> If I add each of those as an option (if they're not already implemented), should they be separate PRs?

Yes, separate PRs :)
