### ISSUE TITLE
Make it work with the new Twitter website

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#195]
Twitter released their rewritten website, which broke most of the features in this extension. I could use help porting the features to the new UI.

**Comment by biscuitsan** [comment]
Will the extension still be compatible with the old one?

**Comment by sindresorhus** [comment]
No, the intent is to move completely to the new UI.

**Comment by giuseppeg** [comment]
fwiw [refined twitter lite](https://github.com/giuseppeg/refined-twitter-lite) is modular so probably you can fork it and add features to it

**Comment by sindresorhus** [comment]
@giuseppeg https://github.com/sindresorhus/refined-twitter#dont-you-have-another-extension-with-the-same-name

**Comment by giuseppeg** [comment]
@sindresorhus neato!

**Comment by b9AcE** [comment]
I think it might be good to have one version for good old twitter and one for their new worsened web-UI, so that those that use the UA-trick or other methods to revert Twitter's design can still use this extension.
There should reasonably not be much maintenance needed for the good old web-UI, as it would be well tested and probably won't undergo further changes by Twitter.

**Comment by tiansh** [comment]
I had done some research on the UI. By wrapping webpack 4<sup>[1]</sup> and `Object.prototype`, it is possible to get Redux `store`, `React`, `ReactDOM` in page script. By wrapping `React.createElement`, it is possible to get every Components. It is fine to do something before / after `store.dispatch()`'s reducer. And since store is well strutted, it could be used to remove / hide some contents on webpage. But since all Components are compressed. Most Components' name are not available. It is hard to wrap Components' `render` to do something changing the layout.

[1]: Login page is using webpack 3, but inner page is webpack 4.

Something possible with `Redux` reducer wrapper described above:

* Remove promoted tweets, user suggestions, news
* Force use Latest timeline
* Remove Who To Follow section in timeline

**Comment by equinox** [comment]
Any chance it's been decided whether or not the new UI will be handled in this repo, or another? It'd save having to close and reject all the bug reports and PRs in this repo that were at the time accurate and could still be potentially used in conjunction with those extensions that allow you to use the old Twitter UI (while it lasts)?

**Comment by sindresorhus** [comment]
The plan is to only target the new UI.

**Comment by StuartHawkes** [comment]
Refined Twitter Lite works with the new Twitter UI, but it's not flexible. This will get us by until we can update this repo.
[https://github.com/giuseppeg/refined-twitter-lite
](url)

BTW, @sindresorhus I love your work, I find myself using so many of your github projects.

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
