### ISSUE TITLE
Download video/GIF

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-twitter#34]
Add a button to download the video/GIF in a tweet.

**Comment by gdad-s-river** [comment]
I'll work on it.

**Comment by gdad-s-river** [comment]
@sindresorhus @filipekiss 

I did some research and tried. Twitter uses HTTP Live Streaming (HLS) protocol to stream its videos using [MPEG Transport Streams](https://www.wikiwand.com/en/MPEG_transport_stream) (.ts files). Also, their video tags are blob URLs like so – 

```html
<video 
  preload="none" 
  playsinline="" 
  src="blob:https://twitter.com/13f32643-9f8e-4048-a75a-84d124ba8324">
</video>
```
I can't help but think on the lines of 

Somehow listen to `.m3u8` files (which have upcoming .ts file (video streams) addresses), keep fetching .ts files until no more, pass them to a mux (something like [mux.js](https://github.com/videojs/mux.js/)) to get an .mp4 formatted data and then somehow download it. Doing this will be very time consuming I guess?

But at the same time through a simple google search I found https://twdown.net/, which is somehow able to find the .mp4 video file which is streamed on hitting the play button. [Twitter doesn't have an API that one could use to fetch .mp4 files anymore](https://twittercommunity.com/t/retiring-mp4-video-output/66093). I wonder how they are able to do that, or if it's very obvious I'm missing something.

I'm stuck and could use some thought process / resource(s) / direction.

**Comment by filipekiss** [comment]
@gdad-s-river Yeah, it seems that the only way to provide proper video download, for now, would be to make a call to the old API (1.1), get the tweet data and there we could find the link to the MP4 directly instead of the blob. But that would eventually break if (when) Twitter disables that version of the API. twdown.net most likely uses the old API but even if they didn't, having a backend means they can use something like `ffmpeg` to stream from that blob url, save to a temporary file and then download it (but I'd bet they use the old API, at least for now. It's cheaper :P)

Maybe focus on image/gif downloads for now and we'll take a look at this later.

**Comment by sindresorhus** [comment]
> But that would eventually break if (when) Twitter disables that version of the API. 

I'd be fine with using that. I don't think it will go away anytime soon, and we can deal with it then if so.

**Comment by filipekiss** [comment]
Great! Let me know if you need any help with this @gdad-s-river! I'll be glad to help!

**Comment by sindresorhus** [comment]
Closing as this extension is now deprecated: https://github.com/sindresorhus/refined-twitter/commit/8dd9df749d3a4e82c95b2bd6628c8d65f0f72e6c
