### ISSUE TITLE
Got a locked account after installing extension

### ISSUE THREAD

**Issue by gillchristian** [sindresorhus/refined-twitter#45]
After installing and start using the extension my account got locked because abuse of Twitter rules. It happened three times. First two times only asked for a reCAPTCHA but now on the third time it also asked for a SMS confirmation. This had never happened before so I assume is because of this extension.

Is there a way to avoid that? I really like the extension and want to keep using it but not if it's going to get my account locked every few days.

**Comment by filipekiss** [comment]
Hey Christian, thanks for the report.

This is really weird, since you're the first one to report being locked out of your account. The extensions make no requests to twitter api or anything like that, so I hardly think that is the problem.

Could you maybe open a ticket with Twitter and ask them for more information as why they locked your account, so we can look further into this?

Thank you!

**Comment by gillchristian** [comment]
Yeah, sure. I will share what they say.

**Comment by sindresorhus** [comment]
Closing as there have been no other reports of this. I'm still interested in hearing what Twitter replies though.

**Comment by gillchristian** [comment]
My account was automatically unlocked one day after I opened the ticket on their support but I never got an answer from them with the reasons :confused:
