### ISSUE TITLE
Idea: reprioritize the timeline

### ISSUE THREAD

**Issue by ryaninvents** [sindresorhus/refined-twitter#56]
Recently I read [this article](https://medium.com/@getflourish/turning-twitters-feed-on-its-head-9565af1728c8) describing an app that shows your feed in terms of the people you follow, not in terms of the quantity of tweets produced by their combined network. I know it would be a lot of work, but is there interest in having similar functionality in Refined Twitter?

Off the top of my head, you could organize the timeline:
- by people (the way Florian's design concept does)
- by lists
- chronologically
- maybe allow people to set a "weight" for each account, store it in localStorage, then sort by weight/recency similarly to Reddit posts?

I'm not sure how feasible some of these would be because I haven't looked at Twitter's API, but at the very least there might be some interesting discussion leading to an unrelated feature.

**Comment by filipekiss** [comment]
I like the idea, but I'm afraid that would be nearly impossible to maintain this as an extension. Requiring the user to login via twitter so we can use the API and re-order the timeline is basically writing a twitter client, and I'm not sure this is this extension is aiming for that. We want to make twitter itself more pleasant to use, yes, but I'm not sure that's the direction we're aiming for.

**Comment by ryaninvents** [comment]
Ah, that makes sense 😃 I love what you're doing with this extension by the way!

**Comment by joshmanders** [comment]
I came across this because I was looking for similar. I like to follow people but some people just retweet or tweet wayyy to much and often flood my stream with just them. Before this extension I used Tweetbot, and a few times I marked some people as "disable retweets" to hide their retweets and my whole feed became a completely new feed as 27 retweets disappeared.

I'd like to see something that we can add say weight, and that weight can determine some things, like if my current stream has 50 tweets, and 10 of those are retweets by one person, weights could say "This person isn't as important to me, so hide some of those tweets/retweets so more important peoples stuff isn't drowned out"
