### ISSUE TITLE
See <n> new tweets

### ISSUE THREAD

**Issue by rdstach** [sindresorhus/refined-twitter#74]
![screen shot 2018-02-23 at 18 02 13](https://user-images.githubusercontent.com/29869049/36591312-2e7b8f00-18c4-11e8-80c4-e2ecad3d947e.png)

> I still have to scroll up to let the twitter feed update itself.

I thought it would be automatically, even though I didn't have to click the button, I'd still have to scroll the way up.

**Comment by rdstach** [comment]
![screen shot 2018-02-23 at 18 08 26](https://user-images.githubusercontent.com/29869049/36591430-95682462-18c4-11e8-9cfa-298b4c54b6bc.png)

> Another one.

**Comment by filipekiss** [comment]
Unless I misunderstood your problem, this is the intended behavior. It will only load `n` new tweets if you're on top of your stream. If you scroll down your timeline past a threshold, the script will not load everything automatically because that would make your stream "jump" around as new elements would be added to the page. I'll be closing this but feel free to re-open if the problem is something else.

**Comment by sindresorhus** [comment]
Even if we managed to preserve the position, new tweets slow down performance and you don’t want that when scrolling a long feed.
