### ISSUE TITLE
Padding between names

### ISSUE THREAD

**Issue by disinfeqt** [sindresorhus/refined-twitter#75]
Thanks for making this. But after using for a few days, I noticed that the padding between usernames are _apparently_ too big.

<img width="586" alt="screen shot 2018-03-01 at 2 42 58 pm" src="https://user-images.githubusercontent.com/211979/36830573-24a679aa-1d5f-11e8-8f96-6c78f6c40c16.png">

I think they weren't this big until recently, no? Could you explain why is the padding added in the first place?  Also I would suggest reducing the padding to 2px.

Thanks.

**Comment by Hoishin** [comment]
It is caused by this https://github.com/sindresorhus/refined-twitter/blob/61219d0cf01e878873731ccb878b685d2cbffc4e/source/style/content.css#L37

Apparently it is supposed to highlight the mentions?

For comparison:

- macOS High Sierra
- Google Chrome

without the plugin
![screen shot 2018-03-01 at 15 57 35](https://user-images.githubusercontent.com/28832095/36831065-8a704d06-1d69-11e8-8746-00abafc1d3ba.png)


with the plugin
![screen shot 2018-03-01 at 15 57 01](https://user-images.githubusercontent.com/28832095/36831053-7d662266-1d69-11e8-9bf1-a23e66ed21e3.png)

**Comment by filipekiss** [comment]
@sindresorhus Should we keep highlighting handle names on tweets? They're already links and I don't see why keep this padding or any other style on mentions — the feature added by c447589 should not be affected.

**Comment by sindresorhus** [comment]
@filipekiss Yeah, we can remove it.
