### ISSUE TITLE
Broken header

### ISSUE THREAD

**Issue by aolko** [sindresorhus/refined-twitter#78]
![](https://i.gyazo.com/a55b61c954ea74195c4461c86129f50e.png)
pls fix

**Comment by sindresorhus** [comment]
// @gdad-s-river

**Comment by aolko** [comment]
will you push that to chrome web store?

**Comment by sindresorhus** [comment]
It will be out in an hour or so. All commits to master are pushed directly to the Chrome Marketplace (which uses about an hour to update).

**Comment by aolko** [comment]
still nope
![](https://i.imgur.com/ycif4Mp.png)

**Comment by gdad-s-river** [comment]
@aolko It's working fine for me – 

![headerissue](https://user-images.githubusercontent.com/4655633/37019175-554d4b10-213d-11e8-9b21-be61b2174494.gif)

**Comment by aolko** [comment]
@gdad-s-river, maybe check another locales?
Issue occurs on 937+px and if it's supposed to be a full-width header - tough luck, it isn't, width stuck on 820px which shouldn't occur, i think.

**Comment by gdad-s-river** [comment]
@aolko tried a bunch of different locales, all work.

![githubissue](https://user-images.githubusercontent.com/4655633/37046013-51fb7ee6-218d-11e8-9358-083540f0da06.gif)

I had earlier wrongly set the breakpoint to 938px. I corrected it to 936px at which the (icons+texts) <–> (icons) switch happens in the nav (see #79)

The purpose of this was to centre the nav widgets (see #57), since refined-twitter removes left and right side widgets.

**Comment by aolko** [comment]
en_US [gifv](https://i.imgur.com/AkBw758.gifv)

ru_RU [gifv](https://i.imgur.com/hnr4hgC.gifv)

think again

**Comment by gdad-s-river** [comment]
@aolko why don't you give it a go? I'm relatively inexperienced in web development at large. I could learn.

**Comment by aolko** [comment]
for me removing (caption of) likes works or just shrink `.global-nav .form-search` to 180px
or remove this stupid limitation 
![image](https://user-images.githubusercontent.com/581458/37353744-06ae6322-26f1-11e8-942b-301afd2ee185.png)
